App\Entity\Language:
  attributes:
    id:
      groups: ['language']
    name:
      groups: ['language']
    ISO:
      groups: [ 'language', 'translation', 'key-translation']
    LTR:
      groups: [ 'language' ]