App\Entity\Translation:
  attributes:
    id:
      groups: ['translation']
    text:
      groups: ['translation', 'key-translation']
    language:
      groups: ['translation', 'language' , 'key-translation']
    keyId:
      groups: ['translation']


